## 数据集

| 表格 | 描述 |  
| --- | --- |  
| index | 每个变量对应的问卷题目，以及变量取值的含义 |  
| survey | 数据源的原版问卷 |   
| *_complete | 变量完整版数据 |   
| *_abbr | 变量精简版数据 |

提交格式：   

| id | happiness |  
| --- | --- |

### 数据集导入

In [1]:
import pandas as pd
import numpy as np

In [15]:
df_indexOrg = pd.read_csv('../Data/happiness_index.csv')
df_indexOrg

,变量名,原始问卷编号,问题,取值含义,精简版
0,-,-,通用含义,-1 = 不适用; -2 = 不知道; -3 = 拒绝回答; -8 = 无法回答;,NaN
1,id,-,编号,-,Y
2,survey_type,s1,样本类型,1 = 城市; 2 = 农村;,Y
3,province,s41,采访地点-省/自治区/直辖市编码,1 = 上海市; 2 = 云南省; 3 = 内蒙古自治区; 4 = 北京市; 5 = 吉林省...,Y
4,city,s42,采访地点-地级市编码,-,Y
5,county,s43,采访地点-县/区编码,-,Y
6,survey_time,a0,问卷当前时间,-,Y
7,gender,a2,您的性别,1 = 男; 2 = 女;,Y
8,birth,a301,您的出生日期-年,-,Y
9,nationality,a4,您的民族,1 = 汉; 2 = 蒙; 3 = 满; 4 = 回; 5 = 藏; 6 = 壮; 7 = ...,Y
10,religion,a501,您的宗教信仰-不信仰宗教,0 = 否; 1 = 是;,Y
11,religion_freq,a6,您参加宗教活动的频繁程度,1 = 从来没有参加过; 2 = 一年不到1次; 3 = 一年大概1到2次; 4 = 一年几...,Y
12,edu,a7a,您目前的最高教育程度（包括目前在读的）,1 = 没有受过任何教育; 2 = 私塾、扫盲班; 3 = 小学; 4 = 初中; 5 = ...,Y
13,edu_other,a7aa,您目前的最高教育程度是-其他,-,N
14,edu_status,a7b,您目前的最高教育程度的状态,1 = 正在读; 2 = 辍学和中途退学; 3 = 肄业; 4 = 毕业;,N
15,edu_yr,a7c,您已经完成的最高学历是哪一年获得的“已完成”指已获得毕业证,-,N
16,income,a8a,您个人去年全年的总收入,9999996 = 个人全年总收入高于百万位数;,Y
17,political,a10,您目前的政治面貌,1 = 群众; 2 = 共青团员; 3 = 民主党派; 4 = 共产党员;,Y
18,join_party,a10a,您目前政治面貌是共产党员，入党时间,-,N
19,floor_area,a11,您现在住的这座住房的套内建筑面积,-,Y
20,property_0,a1299,您现在这座房子的产权属于-无法回答,0 = 否; 1 = 是;,N
21,property_1,a121,您现在这座房子的产权属于-自己所有,0 = 否; 1 = 是;,N
22,property_2,a122,您现在这座房子的产权属于-配偶所有,0 = 否; 1 = 是;,N
23,property_3,a123,您现在这座房子的产权属于-子女所有,0 = 否; 1 = 是;,N
24,property_4,a124,您现在这座房子的产权属于-父母所有,0 = 否; 1 = 是;,N
25,property_5,a125,您现在这座房子的产权属于-配偶父母所有,0 = 否; 1 = 是;,N
26,property_6,a126,您现在这座房子的产权属于-子女配偶所有,0 = 否; 1 = 是;,N
27,property_7,a127,您现在这座房子的产权属于-其他家人/亲戚所有,0 = 否; 1 = 是;,N
28,property_8,a128,您现在这座房子的产权属于-家人/亲戚以外的个人或单位所有，这所房子是租来的,0 = 否; 1 = 是;,N
29,property_other,a12a,您现在这座房子的产权属于-其他，请注明,-,N
...,...,...,...,...,...
111,m_political,a90c,您母亲的政治面貌,1 = 群众; 2 = 共青团员; 3 = 民主党派; 4 = 共产党员;,N
112,m_work_14,a90d,您14岁时母亲的就业状况,1 = 受雇于他人（有固定雇主）; 2 = 全职务农; 3 = 兼业务农，同时从事一些非农工...,N
113,status_peer,b1,与同龄人相比，您本人的社会经济地位怎样,1 = 较高; 2 = 差不多; 3 = 较低;,Y
114,status_3_before,b2,与三年前相比，您的社会经济地位发生了什么变化,1 = 上升了; 2 = 差不多; 3 = 下降了;,Y
115,view,b3,根据您的一般印象您对一些重要事情所持的观点和看法与社会大众一致的时候有多少,1 = 一致的时候非常少; 2 = 一致的时候比较少; 3 = 一般; 4 = 一致的时候比...,Y
116,inc_ability,b5,考虑到您的能力和工作状况，您目前的收入是否合理,1 = 非常合理; 2 = 合理; 3 = 不合理; 4 = 非常不合理;,Y
117,inc_exp,b6,您认为您的年收入达到多少元，您才会比较满意,-,N
118,trust_1,b1001,在不直接涉及金钱利益的一般社会交往/接触中的信任度-(近)邻居,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
119,trust_2,b1002,在不直接涉及金钱利益的一般社会交往/接触中的信任度-(城镇的)远邻/街坊或(乡村)邻居?,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
120,trust_3,b1003,在不直接涉及金钱利益的一般社会交往/接触中的信任度-同村的同姓人士,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
121,trust_4,b1004,在不直接涉及金钱利益的一般社会交往/接触中的信任度-同村的非同姓人士,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
122,trust_5,b1005,在不直接涉及金钱利益的一般社会交往/接触中的信任度-亲戚,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
123,trust_6,b1006,在不直接涉及金钱利益的一般社会交往/接触中的信任度-同事,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
124,trust_7,b1007,在不直接涉及金钱利益的一般社会交往/接触中的信任度-交情不深的朋友/相识,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
125,trust_8,b1008,在不直接涉及金钱利益的一般社会交往/接触中的信任度-老同学,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
126,trust_9,b1009,在不直接涉及金钱利益的一般社会交往/接触中的信任度-在外地相遇的同乡(以同市或同县?,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
127,trust_10,b1010,在不直接涉及金钱利益的一般社会交往/接触中的信任度-一起参加文娱、健身、进修等业余,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
128,trust_11,b1011,在不直接涉及金钱利益的一般社会交往/接触中的信任度-一起参加宗教活动的人士,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
129,trust_12,b1012,在不直接涉及金钱利益的一般社会交往/接触中的信任度-一起参加社会活动/公益活动的人?,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
130,trust_13,b1013,在不直接涉及金钱利益的一般社会交往/接触中的信任度-陌生人,1 = 绝大多数不可信; 2 = 多数不可信; 3 = 可信者与不可信者各半; 4 = 多数...,N
131,neighbor_familiarity,b12,您和邻居，街坊/同村其他居民互相之间的熟悉程度,1 = 非常不熟悉; 2 = 不太熟悉; 3 = 一般; 4 = 比较熟悉; 5 = 非常熟悉;,N
132,public_service_1,b161,综合考虑各个方面，您对于公共教育服务的总体满意度,总分100,N
133,public_service_2,b162,综合考虑各个方面，您对于医疗卫生公共服务的总体满意度,总分100,N
134,public_service_3,b163,综合考虑各个方面，您对于基本住房保障公共服务的总体满意度,总分100,N
135,public_service_4,b164,综合考虑各个方面，您对于社会管理公共服务的总体满意度,总分100,N
136,public_service_5,b165,您对下列公共服务其他各领域的满意度-劳动就业,总分100,N
137,public_service_6,b166,您对下列公共服务其他各领域的满意度-社会保障,总分100,N
138,public_service_7,b167,您对下列公共服务其他各领域的满意度-低保，灾害，流浪乞讨，残疾，孤儿救助等,总分100,N
139,public_service_8,b168,您对下列公共服务其他各领域的满意度-公共文化与体育,总分100,N
140,public_service_9,b169,您对下列公共服务其他各领域的满意度-城乡基础设施,总分100,N

In [8]:
df_trainAbbrOrg = pd.read_csv('../Data/happiness_train_abbr.csv')
df_trainAbbrOrg.tail(3)

,id,happiness,survey_type,province,city,county,survey_time,gender,birth,nationality,...,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability
7997,7998,4,1,16,46,78,2015/8/1 17:48,2,1967,1,...,-2.0,3,2,1,2,3,3,1,4,-8
7998,7999,3,1,1,1,8,2015/9/22 18:52,2,1978,1,...,170000.0,1,3,-1,2,1,2,1,4,2
7999,8000,4,1,1,1,3,2015/9/28 20:22,2,1991,1,...,48000.0,1,3,1,2,1,2,2,3,3

In [9]:
df_trainComOrg = pd.read_csv('../Data/happiness_train_complete.csv')
df_trainComOrg.tail(3)

,id,happiness,survey_type,province,city,county,survey_time,gender,birth,nationality,...,neighbor_familiarity,public_service_1,public_service_2,public_service_3,public_service_4,public_service_5,public_service_6,public_service_7,public_service_8,public_service_9
7997,7998,4,1,16,46,78,2015/8/1 17:48,2,1967,1,...,4,75,70,70,80,80.0,70,75,70,75
7998,7999,3,1,1,1,8,2015/9/22 18:52,2,1978,1,...,2,56,67,70,69,78.0,60,70,80,70
7999,8000,4,1,1,1,3,2015/9/28 20:22,2,1991,1,...,3,80,80,80,80,80.0,80,80,80,80

In [11]:
df_testAbbrOrg = pd.read_csv('../Data/happiness_test_abbr.csv')
df_testAbbrOrg.tail(3)

,id,survey_type,province,city,county,survey_time,gender,birth,nationality,religion,...,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability
2965,10966,2,29,84,127,2015/7/22 9:29,2,1968,1,1,...,30000,2,3,1,2,3,2,1,4,2
2966,10967,1,11,31,54,2015/7/20 16:06,1,1950,1,1,...,-1,2,3,1,2,3,2,1,4,-8
2967,10968,1,13,37,68,2015/9/3 9:59,1,1941,1,1,...,74000,5,3,1,2,3,2,2,4,2

In [14]:
df_testComOrg = pd.read_csv('../Data/happiness_test_complete.csv')
df_testComOrg.tail(3)

,id,survey_type,province,city,county,survey_time,gender,birth,nationality,religion,...,neighbor_familiarity,public_service_1,public_service_2,public_service_3,public_service_4,public_service_5,public_service_6,public_service_7,public_service_8,public_service_9
2965,10966,2,29,84,127,2015/7/22 9:29,2,1968,1,1,...,4,60,60.0,60,60,60,60,60,60,60
2966,10967,1,11,31,54,2015/7/20 16:06,1,1950,1,1,...,3,84,60.0,70,87,90,80,80,80,80
2967,10968,1,13,37,68,2015/9/3 9:59,1,1941,1,1,...,5,90,90.0,90,90,90,90,90,90,90

### 数据集感悟